---
title: "Multidimensional scaling"
output: html_document
---
source: http://www.analytictech.com/borgatti/mds.htm

# MDS for US cities example

```{r setup, warning = FALSE, message = FALSE}
# load libraries 
library(ggplot2)

# read in the data
D <- read.csv("us_cities_distance.csv")
head(D)

# remove first column
D <- D[, -1]

# save number of oberservations
n <- nrow(D)
```

1. Define the centering matrix J 
$$
J = I  - \frac{1}{n}11'
$$
and apply double centering (i.e. compute $B$)

$$
B = -\frac{1}{2} JD^{(2)}J
$$

```{r centering matrix}
# define centering matrix J
I <- diag(1, n)
one <- matrix(1, nrow = n, ncol = n)
J <- I - (1 / n) * one 

# Apply double centering
B <- -(1 / 2) * (J %*% as.matrix(D)^2 %*% J)

# check double centering
apply(B, 1, mean)
apply(B, 2, mean)
```

2. Obtain eigendecomposition of $B$
```{r}
# obtain eigendecomposition of B
eigen_B <- eigen(B)
E <- eigen_B$vectors[, 1:2]
Lambda <- diag(eigen_B$values[1:2])
```

3. Define projected $X$ 
$$
X = E_m\Lambda_m^{1/2}
$$
where $E_m$ is the matrix of $m$ eigenvectors and $\Lambda_m$ is the diagnonal matrix of $m$ eigenvalues.
```{r}
# define projected X
X <- E %*% sqrt(Lambda)
colnames(X) <- c("x", "y")
X <- data.frame(X, city = colnames(D))
```

4. Plot the positions of the cities 
```{r}
# plot the positions of the cities
ggplot(X) + 
  geom_text(aes(x = x, y = y, label = city), size = 8) +
  theme_classic() +
  scale_x_continuous(limits = c(min(X[, 1]) - 1000, max(X[, 1]) + 1000))
```


